# --- Etapa 1: Construcción (Build) ---
# Usamos una imagen de Node para construir el proyecto
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
# Este comando crea la carpeta 'dist' con los archivos de producción
RUN npm run build

# --- Etapa 2: Producción (Serve) ---
# Usamos una imagen ligera de Nginx para servir los archivos
FROM nginx:stable-alpine
# Copiamos los archivos construidos de la etapa anterior a la carpeta web de Nginx
COPY --from=builder /app/dist /usr/share/nginx/html
# Copiamos la configuración de Nginx que crearemos en el siguiente paso
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Exponemos el puerto 80
EXPOSE 80
# El comando por defecto de Nginx se encargará de iniciar el servidor
CMD ["nginx", "-g", "daemon off;"]