#!/bin/bash
# ===================================
# GUÍA RÁPIDA DE EJECUCIÓN
# POS CUADRE - Limpieza y Git Setup
# ===================================

echo "╔════════════════════════════════════════════════════════════════╗"
echo "║          PLAN DE LIMPIEZA Y CONFIGURACIÓN GIT                  ║"
echo "║                    POS CUADRE                                  ║"
echo "╚════════════════════════════════════════════════════════════════╝"
echo ""
echo "Este script NO ejecuta nada, solo muestra los pasos que debes seguir."
echo "Copia y pega cada comando en tu terminal después de revisar."
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 1: REVISAR LOS ARCHIVOS CREADOS"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Revisa el .gitignore creado:"
echo "cat .gitignore"
echo ""
echo "# Revisa la estrategia Git:"
echo "cat GIT_STRATEGY.md"
echo ""
echo "# Revisa el README:"
echo "cat README.md"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 2: EJECUTAR LIMPIEZA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Ejecuta el script de limpieza:"
echo "./cleanup.sh"
echo ""
echo "# Esto moverá todos los respaldos a _respaldos_locales/"
echo "# y corregirá la estructura anidada de frontend/"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 3: CONFIGURAR VARIABLES DE ENTORNO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Backend: Revisa si necesitas actualizar credenciales"
echo "nano backend/.env"
echo ""
echo "# Si tienes credenciales de producción guardadas:"
echo "# cat backend/.env.production.backup"
echo ""
echo "# Frontend: Actualiza la URL de la API si es necesario"
echo "nano frontend/.env.development"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 4: INICIALIZAR GIT"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Inicializar repositorio Git"
echo "git init"
echo ""
echo "# Configurar usuario (si no lo has hecho)"
echo "git config user.name \"Tu Nombre\""
echo "git config user.email \"tu@email.com\""
echo ""
echo "# Crear rama develop (rama de trabajo principal)"
echo "git checkout -b develop"
echo ""
echo "# Añadir todos los archivos"
echo "git add ."
echo ""
echo "# Ver qué se va a commitear"
echo "git status"
echo ""
echo "# Primer commit"
echo 'git commit -m "feat: Initial commit - Proyecto limpio y estructurado

- Estructura backend/ y frontend/ estandarizada
- .gitignore configurado
- Docker Compose para dev y prod
- Documentación completa (README, GIT_STRATEGY)
- Archivos de respaldo movidos a _respaldos_locales/"'
echo ""
echo "# Crear rama main desde develop"
echo "git branch main"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 5: CONECTAR CON GITHUB (OPCIONAL)"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# 1. Crea un repositorio en GitHub (VACÍO, sin README ni .gitignore)"
echo "#    https://github.com/new"
echo ""
echo "# 2. Conecta tu repositorio local con GitHub:"
echo "git remote add origin https://github.com/TU_USUARIO/pos-cuadre.git"
echo ""
echo "# 3. Sube ambas ramas:"
echo "git push -u origin main"
echo "git push -u origin develop"
echo ""
echo "# 4. Configura develop como rama por defecto en GitHub:"
echo "#    Settings → Branches → Default branch → develop"
echo ""
echo "# 5. Protege la rama main:"
echo "#    Settings → Branches → Add rule → main"
echo "#    ✅ Require a pull request before merging"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 6: VERIFICAR QUE TODO FUNCIONA"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Levantar entorno de desarrollo con Docker"
echo "docker-compose up -d"
echo ""
echo "# Ver logs del backend"
echo "docker-compose logs -f backend"
echo ""
echo "# Acceder a:"
echo "#   - Backend API: http://localhost:4000"
echo "#   - phpMyAdmin:  http://localhost:8084"
echo ""
echo "# Si desarrollas sin Docker:"
echo "cd backend && npm install && npm run dev"
echo "# En otra terminal:"
echo "cd frontend && npm install && npm run dev"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "PASO 7: FLUJO DE TRABAJO DIARIO"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Crear nueva característica:"
echo "git checkout develop"
echo "git pull origin develop"
echo "git checkout -b feature/nombre-descriptivo"
echo ""
echo "# Trabajar en tu código..."
echo "# Cuando termines:"
echo "git add ."
echo 'git commit -m "feat: descripción del cambio"'
echo "git push -u origin feature/nombre-descriptivo"
echo ""
echo "# Luego en GitHub: Crear Pull Request → feature/nombre → develop"
echo ""
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "COMANDOS ÚTILES"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "# Ver estado del repositorio"
echo "git status"
echo ""
echo "# Ver diferencias antes de commit"
echo "git diff"
echo ""
echo "# Ver historial de commits"
echo "git log --oneline --graph --all"
echo ""
echo "# Cambiar de rama"
echo "git checkout develop"
echo ""
echo "# Listar todas las ramas"
echo "git branch -a"
echo ""
echo "# Ver qué ignorará Git"
echo "git status --ignored"
echo ""
echo ""
echo "╔════════════════════════════════════════════════════════════════╗"
echo "║                    ¡LISTO PARA COMENZAR!                       ║"
echo "║  Consulta GIT_STRATEGY.md para más detalles sobre el flujo    ║"
echo "╚════════════════════════════════════════════════════════════════╝"
